INSERT INTO `` (`id`,`nombre`,`precio`,`imagen`,`descripcion`,`stock`,`categoria_id`) VALUES (1,'Buzo Básico Algodón',12990,'buzo_basico.jpg',NULL,2,6);
INSERT INTO `` (`id`,`nombre`,`precio`,`imagen`,`descripcion`,`stock`,`categoria_id`) VALUES (2,'Buzo Básico Negro',15990,'buzo_basico_negro.jpg',NULL,3,6);
INSERT INTO `` (`id`,`nombre`,`precio`,`imagen`,`descripcion`,`stock`,`categoria_id`) VALUES (3,'Buzo Joggers Negro',17990,'buzo_joggers_negro.jpg',NULL,15,6);
INSERT INTO `` (`id`,`nombre`,`precio`,`imagen`,`descripcion`,`stock`,`categoria_id`) VALUES (4,'Buzo Básico Azul',19990,'buzo_basico_azul.jpg',NULL,15,6);
INSERT INTO `` (`id`,`nombre`,`precio`,`imagen`,`descripcion`,`stock`,`categoria_id`) VALUES (5,'Poleron Básica Algodón',12990,'poleron_basico.jpg',NULL,15,3);
INSERT INTO `` (`id`,`nombre`,`precio`,`imagen`,`descripcion`,`stock`,`categoria_id`) VALUES (6,'Poleron Negro Estampado',15990,'poleron_negro_estampado.jpg',NULL,15,3);
INSERT INTO `` (`id`,`nombre`,`precio`,`imagen`,`descripcion`,`stock`,`categoria_id`) VALUES (7,'Poleron Beige Simple',17990,'poleron_beige_simple.jpg',NULL,15,3);
INSERT INTO `` (`id`,`nombre`,`precio`,`imagen`,`descripcion`,`stock`,`categoria_id`) VALUES (8,'Poleron Verde Estampado',19990,'poleron_verde_estampado.jpg',NULL,15,3);
INSERT INTO `` (`id`,`nombre`,`precio`,`imagen`,`descripcion`,`stock`,`categoria_id`) VALUES (9,'Polera Básica Algodón',12990,'polera_basica.jpg',NULL,15,1);
INSERT INTO `` (`id`,`nombre`,`precio`,`imagen`,`descripcion`,`stock`,`categoria_id`) VALUES (10,'Polera Básica Blanca',15990,'polera_blanca.jpg',NULL,15,1);
INSERT INTO `` (`id`,`nombre`,`precio`,`imagen`,`descripcion`,`stock`,`categoria_id`) VALUES (11,'Polera Básica Negra',17990,'polera_negra.jpg',NULL,15,1);
INSERT INTO `` (`id`,`nombre`,`precio`,`imagen`,`descripcion`,`stock`,`categoria_id`) VALUES (12,'Polera Beige Estampada',19990,'polera_beige_estampado.jpg',NULL,15,1);
INSERT INTO `` (`id`,`nombre`,`precio`,`imagen`,`descripcion`,`stock`,`categoria_id`) VALUES (13,'Pantalón Básico Algodón',12990,'pantalon_basico.jpg',NULL,15,5);
INSERT INTO `` (`id`,`nombre`,`precio`,`imagen`,`descripcion`,`stock`,`categoria_id`) VALUES (14,'Pantalón Jean Simple',15990,'pantalon_jean_basico.jpg',NULL,15,5);
INSERT INTO `` (`id`,`nombre`,`precio`,`imagen`,`descripcion`,`stock`,`categoria_id`) VALUES (15,'Pantalón Jean Gris Estampado',17990,'pantalon_jean_gris_estampado.jpg',NULL,15,5);
INSERT INTO `` (`id`,`nombre`,`precio`,`imagen`,`descripcion`,`stock`,`categoria_id`) VALUES (16,'Pantalón Jean Negro Simple',19990,'pantalon_jean_negro_basico.jpg',NULL,15,5);
INSERT INTO `` (`id`,`nombre`,`precio`,`imagen`,`descripcion`,`stock`,`categoria_id`) VALUES (17,'Chaqueta Básica Algodón',12990,'chaqueta_basica.jpg',NULL,15,4);
INSERT INTO `` (`id`,`nombre`,`precio`,`imagen`,`descripcion`,`stock`,`categoria_id`) VALUES (18,'Abrigo Beige Simple',15990,'chaqueta_abrigo_beige_basico.jpg',NULL,15,4);
INSERT INTO `` (`id`,`nombre`,`precio`,`imagen`,`descripcion`,`stock`,`categoria_id`) VALUES (19,'Chaqueta Cuero Negra',17990,'chaqueta_cuero_negra.jpg',NULL,15,4);
INSERT INTO `` (`id`,`nombre`,`precio`,`imagen`,`descripcion`,`stock`,`categoria_id`) VALUES (20,'Chaqueta Marrón Simple',19990,'chaqueta_marron_basica.jpg',NULL,15,4);
INSERT INTO `` (`id`,`nombre`,`precio`,`imagen`,`descripcion`,`stock`,`categoria_id`) VALUES (21,'Camisa Básica Algodón',12990,'camisa_basica.jpg',NULL,15,2);
INSERT INTO `` (`id`,`nombre`,`precio`,`imagen`,`descripcion`,`stock`,`categoria_id`) VALUES (22,'Camisa Marrón',15990,'camisa_marron.jpg',NULL,15,2);
INSERT INTO `` (`id`,`nombre`,`precio`,`imagen`,`descripcion`,`stock`,`categoria_id`) VALUES (23,'Camisa Azul',17990,'camisa_azul.jpg',NULL,15,2);
INSERT INTO `` (`id`,`nombre`,`precio`,`imagen`,`descripcion`,`stock`,`categoria_id`) VALUES (24,'Camisa Guayabera',19990,'camisa_guayabera.jpg',NULL,15,2);
